runs:
  using: "composite"
  steps:
    - run: |
        set -x
        echo '${{ github.action_path }}'
        ap=$(cygpath -u '${{ github.action_path }}')
        echo "$ap"
        BASH_HELPERS="$ap/helpers.sh"
        echo "$BASH_HELPERS"
        echo "BASH_HELPERS=$BASH_HELPERS" >> $GITHUB_ENV
      shell: bash
      if: runner.os == 'Windows'
    - run: |
        set -x
        BASH_HELPERS="${{ github.action_path }}/helpers.sh"
        echo "$BASH_HELPERS"
        echo "BASH_HELPERS=$BASH_HELPERS" >> $GITHUB_ENV
      shell: bash
      if: runner.os != 'Windows'
