runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -Eeuo pipefail
        if [[ $RUNNER_OS == "Windows" ]]; then
            ap=$(cygpath -u '${{ github.action_path }}')
        else
            ap='${{ github.action_path }}'
        fi
        BASH_HELPERS="$ap/helpers.sh"
        echo "BASH_HELPERS=$BASH_HELPERS" >> "$GITHUB_ENV"
