name: Test bash-helpers
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  setup-solvers-github:
    strategy:
      matrix:
        os:
          - windows-2019
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-11.0
          - macos-10.15
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      Z3_VERSION: "4.8.8"
      CVC4_VERSION: "1.8"
      YICES_VERSION: "2.6.2"
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - shell: bash
        run: |
          source "$BASH_HELPERS"
          setup-solvers-github
          z3 --version | grep -q $Z3_VERSION
          cvc4 --version | grep -q $CVC4_VERSION
          yices --version | grep -q $YICES_VERSION
          yices-sat --version | grep -q $YICES_VERSION
          yices-smt --version | grep -q $YICES_VERSION
          yices-smt2 --version | grep -q $YICES_VERSION
      - shell: bash
        run: |
          z3 --version | grep -q $Z3_VERSION
          cvc4 --version | grep -q $CVC4_VERSION
          yices --version | grep -q $YICES_VERSION
          yices-sat --version | grep -q $YICES_VERSION
          yices-smt --version | grep -q $YICES_VERSION
          yices-smt2 --version | grep -q $YICES_VERSION
