name: Test bash-helpers
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  solvers-native:
    strategy:
      matrix:
        os:
          # - windows-2019
          - ubuntu-18.04
          # - macos-10.15
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      Z3_VERSION: "4.8.8"
      CVC4_VERSION: "1.8"
      YICES_VERSION: "2.6.2"
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - shell: bash
        run: |
          set -Eeuo pipefail
          set -x
          echo "$BASH_HELPERS"
          source "$BASH_HELPERS"
          setup-solvers-github
          echo $PATH
          z3 --version || true
          cvc4 --version || true
          yices --version | grep -q $YICES_VERSION
          yices-sat --version | grep -q $YICES_VERSION
          yices-smt --version | grep -q $YICES_VERSION
          yices-smt2 --version | grep -q $YICES_VERSION
      - shell: bash
        run: |
          echo $PATH
          z3 --version || true
          cvc4 --version || true
          yices --version || true
          yices --version | grep -q $YICES_VERSION
          yices-sat --version | grep -q $YICES_VERSION
          yices-smt --version | grep -q $YICES_VERSION
          yices-smt2 --version | grep -q $YICES_VERSION
