name: Test bash-helpers
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  github-setup-solvers:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-11.0
          - macos-10.15
    runs-on: ${{ matrix.os }}
    env:
      Z3_VERSION: "4.8.8"
      CVC4_VERSION: "1.8"
      YICES_VERSION: "2.6.2"
      YASM_VERSION: "pkgmgr-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Setup and test solvers
        shell: bash
        run: |
          set -Eeuo pipefail
          source "$BASH_HELPERS"
          github-setup-solvers
          z3 --version | grep -q $Z3_VERSION
          cvc4 --version | grep -q $CVC4_VERSION
          yices --version | grep -q $YICES_VERSION
          yasm --version
      - name: Check solver usability from later step
        shell: bash
        run: |
          z3 --version | grep -q $Z3_VERSION
          cvc4 --version | grep -q $CVC4_VERSION
          yices --version | grep -q $YICES_VERSION
          yasm --version
